name: fatah_workshop
description: A simple workshop desktop application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons:
  shared_preferences:
  bitsdojo_window:
  intl:
  get:
  fluentui_system_icons:
  responsive_grid_list:
  fl_chart:
  sqflite:
  multi_image_picker_view:
  sqflite_common_ffi:
  sqflite_common:
  easy_image_viewer:
  path_provider:
  mime:
  dart_random_choice:
  another_transformer_page_view:
  file_picker:

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter_launcher_icons:
    windows:
      generate: true
      image_path: "images/light_logo.png"
      icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Anton
      fonts:
        - asset: fonts/Anton-Regular.ttf
    - family: Audiowide
      fonts:
          - asset: fonts/Audiowide-Regular.ttf
